/*
 * This file is generated by jOOQ.
 */
package net.ttcxy.chat.db.tables.records;


import java.time.LocalDateTime;

import net.ttcxy.chat.db.tables.Group;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupRecord extends TableRecordImpl<GroupRecord> implements Record3<String, String, LocalDateTime> {

    private static final long serialVersionUID = -1487872111;

    /**
     * Setter for <code>chat.group.id</code>.
     */
    public GroupRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>chat.group.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>chat.group.name</code>.
     */
    public GroupRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>chat.group.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>chat.group.create_time</code>.
     */
    public GroupRecord setCreateTime(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>chat.group.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Group.GROUP.ID;
    }

    @Override
    public Field<String> field2() {
        return Group.GROUP.NAME;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Group.GROUP.CREATE_TIME;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateTime();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateTime();
    }

    @Override
    public GroupRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public GroupRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GroupRecord value3(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public GroupRecord values(String value1, String value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupRecord
     */
    public GroupRecord() {
        super(Group.GROUP);
    }

    /**
     * Create a detached, initialised GroupRecord
     */
    public GroupRecord(String id, String name, LocalDateTime createTime) {
        super(Group.GROUP);

        set(0, id);
        set(1, name);
        set(2, createTime);
    }
}
