/*
 * This file is generated by jOOQ.
 */
package net.ttcxy.chat.db.tables.records;


import java.time.LocalDateTime;

import net.ttcxy.chat.db.tables.GroupMember;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupMemberRecord extends TableRecordImpl<GroupMemberRecord> implements Record4<String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 224061282;

    /**
     * Setter for <code>chat.group_member.id</code>.
     */
    public GroupMemberRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>chat.group_member.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>chat.group_member.group_id</code>.
     */
    public GroupMemberRecord setGroupId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>chat.group_member.group_id</code>.
     */
    public String getGroupId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>chat.group_member.member_id</code>.
     */
    public GroupMemberRecord setMemberId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>chat.group_member.member_id</code>.
     */
    public String getMemberId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>chat.group_member.create_time</code>.
     */
    public GroupMemberRecord setCreateTime(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>chat.group_member.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return GroupMember.GROUP_MEMBER.ID;
    }

    @Override
    public Field<String> field2() {
        return GroupMember.GROUP_MEMBER.GROUP_ID;
    }

    @Override
    public Field<String> field3() {
        return GroupMember.GROUP_MEMBER.MEMBER_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return GroupMember.GROUP_MEMBER.CREATE_TIME;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getGroupId();
    }

    @Override
    public String component3() {
        return getMemberId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getGroupId();
    }

    @Override
    public String value3() {
        return getMemberId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    @Override
    public GroupMemberRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public GroupMemberRecord value2(String value) {
        setGroupId(value);
        return this;
    }

    @Override
    public GroupMemberRecord value3(String value) {
        setMemberId(value);
        return this;
    }

    @Override
    public GroupMemberRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public GroupMemberRecord values(String value1, String value2, String value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupMemberRecord
     */
    public GroupMemberRecord() {
        super(GroupMember.GROUP_MEMBER);
    }

    /**
     * Create a detached, initialised GroupMemberRecord
     */
    public GroupMemberRecord(String id, String groupId, String memberId, LocalDateTime createTime) {
        super(GroupMember.GROUP_MEMBER);

        set(0, id);
        set(1, groupId);
        set(2, memberId);
        set(3, createTime);
    }
}
