/*
 * This file is generated by jOOQ.
 */
package net.ttcxy.chat.db.tables.records;


import java.time.LocalDateTime;

import net.ttcxy.chat.db.tables.Member;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberRecord extends TableRecordImpl<MemberRecord> implements Record6<String, String, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 2058842250;

    /**
     * Setter for <code>chat.member.id</code>.
     */
    public MemberRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>chat.member.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>chat.member.username</code>.
     */
    public MemberRecord setUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>chat.member.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>chat.member.nickname</code>.
     */
    public MemberRecord setNickname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>chat.member.nickname</code>.
     */
    public String getNickname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>chat.member.mail</code>.
     */
    public MemberRecord setMail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>chat.member.mail</code>.
     */
    public String getMail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>chat.member.password</code>.
     */
    public MemberRecord setPassword(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>chat.member.password</code>.
     */
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>chat.member.create_time</code>.
     */
    public MemberRecord setCreateTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>chat.member.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, String, String, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Member.MEMBER.ID;
    }

    @Override
    public Field<String> field2() {
        return Member.MEMBER.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return Member.MEMBER.NICKNAME;
    }

    @Override
    public Field<String> field4() {
        return Member.MEMBER.MAIL;
    }

    @Override
    public Field<String> field5() {
        return Member.MEMBER.PASSWORD;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Member.MEMBER.CREATE_TIME;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getNickname();
    }

    @Override
    public String component4() {
        return getMail();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public LocalDateTime component6() {
        return getCreateTime();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getNickname();
    }

    @Override
    public String value4() {
        return getMail();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public LocalDateTime value6() {
        return getCreateTime();
    }

    @Override
    public MemberRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public MemberRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public MemberRecord value3(String value) {
        setNickname(value);
        return this;
    }

    @Override
    public MemberRecord value4(String value) {
        setMail(value);
        return this;
    }

    @Override
    public MemberRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public MemberRecord value6(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public MemberRecord values(String value1, String value2, String value3, String value4, String value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberRecord
     */
    public MemberRecord() {
        super(Member.MEMBER);
    }

    /**
     * Create a detached, initialised MemberRecord
     */
    public MemberRecord(String id, String username, String nickname, String mail, String password, LocalDateTime createTime) {
        super(Member.MEMBER);

        set(0, id);
        set(1, username);
        set(2, nickname);
        set(3, mail);
        set(4, password);
        set(5, createTime);
    }
}
