package net.ttcxy.chat.mapper;

import java.util.List;
import net.ttcxy.chat.entity.model.GangMember;
import net.ttcxy.chat.entity.model.GangMemberExample;
import org.apache.ibatis.annotations.Param;

public interface GangMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_member
     *
     * @mbg.generated Wed Dec 01 20:25:35 CST 2021
     */
    long countByExample(GangMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_member
     *
     * @mbg.generated Wed Dec 01 20:25:35 CST 2021
     */
    int deleteByExample(GangMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_member
     *
     * @mbg.generated Wed Dec 01 20:25:35 CST 2021
     */
    int insert(GangMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_member
     *
     * @mbg.generated Wed Dec 01 20:25:35 CST 2021
     */
    int insertSelective(GangMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_member
     *
     * @mbg.generated Wed Dec 01 20:25:35 CST 2021
     */
    List<GangMember> selectByExample(GangMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_member
     *
     * @mbg.generated Wed Dec 01 20:25:35 CST 2021
     */
    int updateByExampleSelective(@Param("record") GangMember record, @Param("example") GangMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_member
     *
     * @mbg.generated Wed Dec 01 20:25:35 CST 2021
     */
    int updateByExample(@Param("record") GangMember record, @Param("example") GangMemberExample example);
}