package net.ttcxy.chat.mapper;

import java.util.List;
import net.ttcxy.chat.entity.model.GroupMember;
import net.ttcxy.chat.entity.model.GroupMemberExample;
import org.apache.ibatis.annotations.Param;

public interface GroupMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    long countByExample(GroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int deleteByExample(GroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int insert(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int insertSelective(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    List<GroupMember> selectByExample(GroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int updateByExampleSelective(@Param("record") GroupMember record, @Param("example") GroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int updateByExample(@Param("record") GroupMember record, @Param("example") GroupMemberExample example);
}