package net.ttcxy.chat.mapper;

import java.util.List;
import net.ttcxy.chat.entity.model.Group;
import net.ttcxy.chat.entity.model.GroupExample;
import org.apache.ibatis.annotations.Param;

public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    long countByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int deleteByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    List<Group> selectByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int updateByExampleSelective(@Param("record") Group record, @Param("example") GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int updateByExample(@Param("record") Group record, @Param("example") GroupExample example);
}