package net.ttcxy.chat.mapper;

import java.util.List;
import net.ttcxy.chat.entity.model.Member;
import net.ttcxy.chat.entity.model.MemberExample;
import org.apache.ibatis.annotations.Param;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    long countByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int deleteByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    List<Member> selectByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int updateByExampleSelective(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    int updateByExample(@Param("record") Member record, @Param("example") MemberExample example);
}