/*
 * This file is generated by jOOQ.
 */
package net.ttcxy.chat.db;


import java.util.Arrays;
import java.util.List;

import net.ttcxy.chat.db.tables.Group;
import net.ttcxy.chat.db.tables.GroupMember;
import net.ttcxy.chat.db.tables.Member;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chat extends SchemaImpl {

    private static final long serialVersionUID = -1310414412;

    /**
     * The reference instance of <code>chat</code>
     */
    public static final Chat CHAT = new Chat();

    /**
     * The table <code>chat.group</code>.
     */
    public final Group GROUP = Group.GROUP;

    /**
     * The table <code>chat.group_member</code>.
     */
    public final GroupMember GROUP_MEMBER = GroupMember.GROUP_MEMBER;

    /**
     * The table <code>chat.member</code>.
     */
    public final Member MEMBER = Member.MEMBER;

    /**
     * No further instances allowed
     */
    private Chat() {
        super("chat", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Group.GROUP,
            GroupMember.GROUP_MEMBER,
            Member.MEMBER);
    }
}
