/*
 * This file is generated by jOOQ.
 */
package net.ttcxy.chat.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupMember implements Serializable {

    private static final long serialVersionUID = 1218088337;

    private String        id;
    private String        groupId;
    private String        memberId;
    private LocalDateTime createTime;

    public GroupMember() {}

    public GroupMember(GroupMember value) {
        this.id = value.id;
        this.groupId = value.groupId;
        this.memberId = value.memberId;
        this.createTime = value.createTime;
    }

    public GroupMember(
        String        id,
        String        groupId,
        String        memberId,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.groupId = groupId;
        this.memberId = memberId;
        this.createTime = createTime;
    }

    public String getId() {
        return this.id;
    }

    public GroupMember setId(String id) {
        this.id = id;
        return this;
    }

    public String getGroupId() {
        return this.groupId;
    }

    public GroupMember setGroupId(String groupId) {
        this.groupId = groupId;
        return this;
    }

    public String getMemberId() {
        return this.memberId;
    }

    public GroupMember setMemberId(String memberId) {
        this.memberId = memberId;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public GroupMember setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GroupMember (");

        sb.append(id);
        sb.append(", ").append(groupId);
        sb.append(", ").append(memberId);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
