/*
 * This file is generated by jOOQ.
 */
package net.ttcxy.chat.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Group implements Serializable {

    private static final long serialVersionUID = 1704810233;

    private String        id;
    private String        name;
    private LocalDateTime createTime;

    public Group() {}

    public Group(Group value) {
        this.id = value.id;
        this.name = value.name;
        this.createTime = value.createTime;
    }

    public Group(
        String        id,
        String        name,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.name = name;
        this.createTime = createTime;
    }

    public String getId() {
        return this.id;
    }

    public Group setId(String id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Group setName(String name) {
        this.name = name;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public Group setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Group (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
