/*
 * This file is generated by jOOQ.
 */
package net.ttcxy.chat.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Member implements Serializable {

    private static final long serialVersionUID = 83978865;

    private String        id;
    private String        username;
    private String        password;
    private LocalDateTime createTime;

    public Member() {}

    public Member(Member value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.createTime = value.createTime;
    }

    public Member(
        String        id,
        String        username,
        String        password,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.createTime = createTime;
    }

    public String getId() {
        return this.id;
    }

    public Member setId(String id) {
        this.id = id;
        return this;
    }

    public String getUsername() {
        return this.username;
    }

    public Member setUsername(String username) {
        this.username = username;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public Member setPassword(String password) {
        this.password = password;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public Member setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Member (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
