/*
 * This file is generated by jOOQ.
 */
package net.ttcxy.chat.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Message implements Serializable {

    private static final long serialVersionUID = 1320409826;

    private String        id;
    private String        from;
    private String        to;
    private String        text;
    private Integer       type;
    private LocalDateTime createTime;

    public Message() {}

    public Message(Message value) {
        this.id = value.id;
        this.from = value.from;
        this.to = value.to;
        this.text = value.text;
        this.type = value.type;
        this.createTime = value.createTime;
    }

    public Message(
        String        id,
        String        from,
        String        to,
        String        text,
        Integer       type,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.from = from;
        this.to = to;
        this.text = text;
        this.type = type;
        this.createTime = createTime;
    }

    public String getId() {
        return this.id;
    }

    public Message setId(String id) {
        this.id = id;
        return this;
    }

    public String getFrom() {
        return this.from;
    }

    public Message setFrom(String from) {
        this.from = from;
        return this;
    }

    public String getTo() {
        return this.to;
    }

    public Message setTo(String to) {
        this.to = to;
        return this;
    }

    public String getText() {
        return this.text;
    }

    public Message setText(String text) {
        this.text = text;
        return this;
    }

    public Integer getType() {
        return this.type;
    }

    public Message setType(Integer type) {
        this.type = type;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public Message setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Message (");

        sb.append(id);
        sb.append(", ").append(from);
        sb.append(", ").append(to);
        sb.append(", ").append(text);
        sb.append(", ").append(type);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
