package net.ttcxy.chat.entity.model;

import java.io.Serializable;
import java.util.Date;

public class GroupMember implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.id
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.group_id
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.member_id
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.create_time
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.id
     *
     * @return the value of group_member.id
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.id
     *
     * @param id the value for group_member.id
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.group_id
     *
     * @return the value of group_member.group_id
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.group_id
     *
     * @param groupId the value for group_member.group_id
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.member_id
     *
     * @return the value of group_member.member_id
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.member_id
     *
     * @param memberId the value for group_member.member_id
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.create_time
     *
     * @return the value of group_member.create_time
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.create_time
     *
     * @param createTime the value for group_member.create_time
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 29 22:22:55 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", groupId=").append(groupId);
        sb.append(", memberId=").append(memberId);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}