package net.ttcxy.chat.entity.model;

import java.io.Serializable;
import java.util.Date;

public class Member implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.username
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.password
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_time
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.gender
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.usernametwo
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    private String usernametwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.letters
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    private Boolean letters;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.avatar
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.introduction
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.username
     *
     * @return the value of member.username
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.username
     *
     * @param username the value for member.username
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.password
     *
     * @return the value of member.password
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.password
     *
     * @param password the value for member.password
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_time
     *
     * @return the value of member.create_time
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_time
     *
     * @param createTime the value for member.create_time
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gender
     *
     * @return the value of member.gender
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gender
     *
     * @param gender the value for member.gender
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.usernametwo
     *
     * @return the value of member.usernametwo
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public String getUsernametwo() {
        return usernametwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.usernametwo
     *
     * @param usernametwo the value for member.usernametwo
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public void setUsernametwo(String usernametwo) {
        this.usernametwo = usernametwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.letters
     *
     * @return the value of member.letters
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public Boolean getLetters() {
        return letters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.letters
     *
     * @param letters the value for member.letters
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public void setLetters(Boolean letters) {
        this.letters = letters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.avatar
     *
     * @return the value of member.avatar
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.avatar
     *
     * @param avatar the value for member.avatar
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.introduction
     *
     * @return the value of member.introduction
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.introduction
     *
     * @param introduction the value for member.introduction
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Fri Dec 03 10:26:59 GMT+08:00 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", createTime=").append(createTime);
        sb.append(", gender=").append(gender);
        sb.append(", usernametwo=").append(usernametwo);
        sb.append(", letters=").append(letters);
        sb.append(", avatar=").append(avatar);
        sb.append(", introduction=").append(introduction);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}